controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

dashboard:
    path: /admin1
    controller: App\Controller\Admin\DashboardController::index

# api/config/routes.yaml
authentication_token:
    path: /api/login
    methods: ['POST']