name: CD
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      SSHPASS: ${{secrets.APP_PASS}}

    steps:
      - uses: actions/checkout@v2
      - name: APT UPDATE and INSTALL SSHPASS
        run: 
          sudo apt update && sudo apt install sshpass
      - name: GIT CONFIG
        run: 
          git config --global user.name "madanihoussem" && git config --global user.email "madanihoussem98@gmail.com" && git remote set-url origin https://madanihoussem:{{secrets.APP_PASS}}@github.com/madanihoussem/DevBuddy.git
      - name: test pwd
        run:
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd clickandbuilds/DevBuddy && 
          git pull &&
          composer install &&
          php bin/console d:m:m -n"