
name: Deploy Script
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: APT UPDATE and INSTALL SSHPASS
        run: 
          sudo apt update && sudo apt install sshpass
      
      - name: SFTP Sync
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: access795565821.webspace-data.io
          port: 22
          user: u98339934
          # Private SSH key for user (include via secrets if possible)
          user_private_key: ${{ secrets.PRIVATE_KEY }}
          # Public SSH key of host
          host_public_key: ${{ secrets.PUBLIC_KEY }} 
          # Local path to sync (default: .)
          local: .
          # Path on server (default: .)
          remote: /clickandbuilds/DevBuddy
