
name: Deploy Script
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: FTP/SFTP file deployer
        # You may pin to the exact commit or the version.
        # uses: milanmk/actions-file-deployer@58030c10c50a8577d08cef33e47c23bcbbf78c33
        uses: milanmk/actions-file-deployer@1.11
        with:
          # Remote file transfer protocol (ftp, sftp)
          remote-protocol: sftp
          # Remote host
          remote-host: ${{secrets.APP_HOST}}
          # Remote port
          remote-port: 22
          # FTP/SSH username
          remote-user: ${{secrets.APP_USER}}
          # FTP/SSH password
          remote-password: ${{secrets.APP_PASS}}
          # Enable proxy for FTP connection (true, false)
          proxy: false
          # Local path to repository
          local-path: .
          # Remote path on host
          remote-path: /clickandbuilds/DevBuddy
          # File synchronization (delta, full)
          sync: full
      
      - name: composer update action
        # You may pin to the exact commit or the version.
        # uses: kawax/composer-update-action@ff82e4d675a24bc9ed3c1b764ca1e7392d05d4cc
        uses: kawax/composer-update-action@v3.0.0
      